Add Italian Translation
Jonur/aow-formation-share pull request #17
Opened 2022-01-26 14:34 UTC by melaniedrevet

Contribution to the issue #7

2022-01-28 16:16 UTC, antcalvente requested changes
Hello! 

Thanks a lot for adding the translations for Italian, I've just put some comments for the troops names that don't match the in game name. 
It's important to keep the same name as otherwise it would be really difficult for users to find their troops as it's order alphabetically and they'll expect to find the same exact name

Once fixed we'll merge the changes and activate Italian on the site :)

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "zX4n": "Sacro spadaccino",
`Spadaccino Sacro`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "PA95": "Carro armato"
`Tank`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "Hei3": "Tiratore scelto",
`Tiratore`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "Xfwz": "Alchimista pazzo - Hohenheim",
`Alchimista folle - Hohenheim`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "DZGh": "Albero della vita - Verde",
`Albero della vita - Green`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "WiY9": "Cacciatore della giungla - Diana",
`Cacciatrice della Giungla - Diana`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "j1ym": "Frost Baron - Kelvin",
`Barone di Guiaccio - Kelvins`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "9bv9": "Barba Nera - Edoardo",
`Barbanera - Edward`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "nCuH": "Guardiano di Natale - Kriss",
`Gigante del Natale - Kriss`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "5OcS": "Il principe dei ladri - Robin Hood",
`Principe dei Ladri - Robin Hood`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "OQli": "Re Demone Toro - Minotauro",
`Re Toro Demoniaco - Minotauro`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "Zhfz": "Maestro dei Tarocchi - Cassandra",
`Maestra dei Tarocchi - Cassandra`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "CbHd": "Insanguinato lupo mannaro - Miller",
`Lupo Mannaro Succhiasangue - Miller`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "GAcg": "Sakura Blade - Genichiro",
`Sakura Kiru - Genichiro`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "ARHK": "Re del Tuono - Ivan",
`Re dei Fuilmini - Ivan`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "2ZWr": "Orologio - Harrison",
`Orologiaio - Harrison`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "v9oW": "Guardiano dell'Oceano Smeraldo - Poseidone",
`Re dell'Oceano - Poseidone`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "qe78": "Il Re Scimmia - Wukong",
`Re delle Scimmie - Wukong`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "tPKl": "Consiglio ardente - Davison",
`Emissario del Drago - Davison`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "4ZBz": "Duca Scarlatto - Dracula",
`Conte Vampiro - Dracula`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "SaVx": "Royal Christmas Ball - Chione",
`Regina della Terra Ghiacciata - Chione`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "yW9G": "Signore dell'odio - Mefisto",
`Signore dell'Odio - Mephisto`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "7FYw": "Horus il Vecchio - Horus",
`Horus l'Anziano - Horus`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "OJ6m": "Il re di Camelot - Artù",
`Re di Camelot - Arthur`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "NUMk": "Re intrepido - Beowulf",
`Intrepido Re - Beowulf`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "MVQQ": "Grim Reaper - Azrael",
`Tetro Mietitore - Azrael`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "9VqF": "Lancia ardente - Nezha",
`Lancia Infuocata - Nezha`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "AgM6": "Lo spirito della lampada - Jinn",
`Spirito della lampada - Jinn`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "u2TP": "selvaggio",
`Orco`

2022-01-28 16:16 UTC, antcalvente commented on src/i18n/it.json
> +      "T1WD": "Buio"
`Oscuro`

2022-01-28 16:40 UTC, melaniedrevet reviewed
Hello !

Thank you for your feedback, I corrected the troop names as requested ! Indeed, it will be more consistent for users !

2022-01-28 16:45 UTC, antcalvente approved these changes
Thanks for the quick fixes! 

We'll merge it as soon as possible, add you in the list of contributors and then enable the Italian language in the UI

2022-01-29 08:38 UTC, Jonur approved these changes

2022-01-29 08:38 UTC, Jonur commented
Thank you both @melaniedrevet and @antcalvente for this! <3 <3 <3 PR approved and @melaniedrevet I am adding you to the contributors.

2022-02-03 17:00 UTC, merged